DE/ADES/Controllers/DenunciasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ADES.Models;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;
using SendGrid;
using System.Net.Mail;

namespace ADES.Controllers
{
    public class DenunciasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Denuncias/
        public ActionResult Index()
        {
            var denuncias = db.Denuncias.Include(d => d.Denunciante).Include(d => d.TipoDenuncia);
            return View(denuncias.ToList());
        }

        public void SendAsyncDocument(string from, string to, string subject, string body, Stream document, string name)
        {
            string username = "azure_d1ab1a66f08549e4a848e9eee4d49010@azure.com";
            string pswd = "Ozelot2015";
            SendGridMessage myMessage = new SendGridMessage();
            Console.WriteLine("---------------------- Enviado -----------------------");
            myMessage.AddTo(to);
            myMessage.From = new MailAddress(from, "UT-MATEDI");
            myMessage.Subject = subject;
            myMessage.Text = body;
            //myMessage.AddAttachment(@"C:\Users\Moisés Torres\Documents\Visual Studio 2015\Projects\SmartBaby\SmartBaby\Brigada 09-Abril-2016.xlsx");
            myMessage.AddAttachment(document, name);
            var credentials = new NetworkCredential(username, pswd);

            var transportWeb = new Web(credentials);

            transportWeb.DeliverAsync(myMessage);
        }

        public ActionResult IndexUser()
        {
            var idUser = User.Identity.GetUserId();
            var denunciasUSer = db.Denuncias.Include(d => d.Denunciante).Include(d => d.TipoDenuncia).Where(d =>d.idDenunciante == idUser);
            return View(denunciasUSer.ToList());
        }

        public ActionResult Pdf(int? id)
        {
            Denuncia denuncia = db.Denuncias.Find(id);

            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Expediente/Acuse.rpt")));
            rd.SetParameterValue("folio", denuncia.id);
            rd.SetParameterValue("fecha", denuncia.fecha.ToShortDateString());
            rd.SetParameterValue("hora", denuncia.fecha.ToShortTimeString());
            rd.SetParameterValue("denuncia", denuncia.relatoria);
            rd.SetParameterValue("certificado", denuncia.idDenunciante);

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);

            return File(stream, "Application/pdf", "Reporte.pdf");
        }

        // GET: /Denuncias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Denuncia denuncia = db.Denuncias.Find(id);
            if (denuncia == null)
            {
                return HttpNotFound();
            }
            return View(denuncia);
        }

        // GET: /Denuncias/Create
        public ActionResult Create(int id)
        {
            var idUser = User.Identity.GetUserId();
            Denuncia denuncia = new Denuncia();
            denuncia.numExpediente = "000013";
            denuncia.certificado = idUser;
            denuncia.idTipoDenuncia = id;
            denuncia.fecha = DateTime.Now;


            ViewBag.idMinisterioPublico = new SelectList(db.MinisteriosPublicos, "id", "nombre");

   
            return View(denuncia);
        }


        // POST: /Denuncias/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Denuncia denuncia, Responsable responsable, AmpliarDenuncia ad)
        {
            denuncia.idDenunciante = User.Identity.GetUserId();
            denuncia.ipAddress = "192.168.4.210";

            var idUser = User.Identity.GetUserId();
            ApplicationUser usuario = db.Users.Find(idUser);
            
            if (ModelState.IsValid)
            {
                ad.Denuncia = denuncia;
                ad.estatusEvento = EstatusEvento.programado;
                ad.fechaFin = ad.fechaInicio;
                ad.RowVersion = DateTime.Now;
                ad.Denuncia = denuncia;
                responsable.Denuncia = denuncia;
                db.Denuncias.Add(denuncia);
                db.Responsable.Add(responsable);
                db.AmpliacionesDenuncias.Add(ad);
                db.SaveChanges();

                //

                ReportDocument rd = new ReportDocument();
                rd.Load(Path.Combine(Server.MapPath("~/Expediente/Acuse.rpt")));
                rd.SetParameterValue("folio", denuncia.id);
                rd.SetParameterValue("fecha", denuncia.fecha.ToShortDateString());
                rd.SetParameterValue("hora", denuncia.fecha.ToShortTimeString());
                rd.SetParameterValue("denuncia", denuncia.relatoria);
                rd.SetParameterValue("certificado", denuncia.idDenunciante);

                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();
                Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                stream.Seek(0, SeekOrigin.Begin);

                SendAsyncDocument("admin@utancun.edu.mx", usuario.Email, "Acuse", "Hola " + usuario.Email, stream, "Acuse.pdf");

                return RedirectToAction("IndexUser");
            }

            ViewBag.idDenunciante = new SelectList(db.Persona, "id", "nombre", denuncia.idDenunciante);
            ViewBag.idTipoDenuncia = new SelectList(db.TiposDenuncias, "id", "nombre", denuncia.idTipoDenuncia);
			 if (Request.IsAjaxRequest())
                return PartialView(denuncia);
            else
                return View(denuncia);
        }

        // GET: /Denuncias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Denuncia denuncia = db.Denuncias.Find(id);
            if (denuncia == null)
            {
                return HttpNotFound();
            }
            ViewBag.idDenunciante = new SelectList(db.Persona, "id", "nombre", denuncia.idDenunciante);
            ViewBag.idTipoDenuncia = new SelectList(db.TiposDenuncias, "id", "nombre", denuncia.idTipoDenuncia);
 
			 if (Request.IsAjaxRequest())
                return PartialView(denuncia);
            else
                return View(denuncia);
        }

        // POST: /Denuncias/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="id,numExpediente,idDenunciante,idTipoDenuncia,folioC4,relatoria,fecha,certificado,ipAddress,longitud,latitud,aceptacionPoliticas")] Denuncia denuncia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(denuncia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idDenunciante = new SelectList(db.Persona, "id", "nombre", denuncia.idDenunciante);
            ViewBag.idTipoDenuncia = new SelectList(db.TiposDenuncias, "id", "nombre", denuncia.idTipoDenuncia);
            if (Request.IsAjaxRequest())
                return PartialView(denuncia);
            else
                return View(denuncia);
        }

        // GET: /Denuncias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Denuncia denuncia = db.Denuncias.Find(id);
            if (denuncia == null)
            {
                return HttpNotFound();
            }
            return View(denuncia);
        }

        // POST: /Denuncias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Denuncia denuncia = db.Denuncias.Find(id);
            db.Denuncias.Remove(denuncia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult List()
        {
            var tipoDenuncias = db.TiposDenuncias;
            return View(tipoDenuncias.ToList());
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DE/ADES/Controllers/HomeController.cs
using CrystalDecisions.CrystalReports.Engine;
using DotNet.Highcharts;
using DotNet.Highcharts.Enums;
using DotNet.Highcharts.Helpers;
using DotNet.Highcharts.Options;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Web.Mvc;
using SendGrid;
using System.Net.Mail;
using System.Net;
using IdentitySample.Models;

using System.Web.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Identity;
using System.Threading;
using System.Diagnostics;

namespace IdentitySample.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            /*ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Expediente/Acuse.rpt")));
            rd.SetParameterValue("folio", "123");
            rd.SetParameterValue("fecha", DateTime.Now.ToShortDateString());
            rd.SetParameterValue("hora", DateTime.Now.ToShortTimeString());
            rd.SetParameterValue("denuncia", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
            rd.SetParameterValue("certificado", 0);

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);


            SendAsyncDocument("admin@utancun.edu.mx", "gake@ozelot.it", "Acuse", "Hola gerardo", stream, "Acuse.pdf");

            //return File(stream, "Application/pdf", "Reporte.pdf");*/
            return View();
        }

        public void SendAsyncDocument(string from, string to, string subject, string body, Stream document, string name)
        {
            string username = "azure_d1ab1a66f08549e4a848e9eee4d49010@azure.com";
            string pswd = "Ozelot2015";
            SendGridMessage myMessage = new SendGridMessage();
            Console.WriteLine("---------------------- Enviado -----------------------");
            myMessage.AddTo(to);
            myMessage.From = new MailAddress(from, "UT-MATEDI");
            myMessage.Subject = subject;
            myMessage.Text = body;
            //myMessage.AddAttachment(@"C:\Users\Moisés Torres\Documents\Visual Studio 2015\Projects\SmartBaby\SmartBaby\Brigada 09-Abril-2016.xlsx");
            myMessage.AddAttachment(document, name);
            var credentials = new NetworkCredential(username, pswd);

            var transportWeb = new Web(credentials);

            transportWeb.DeliverAsync(myMessage);
        }

        public ActionResult Dashboard()
        {
            string idUser = User.Identity.GetUserId();
            ApplicationUser usuario = db.Users.Find(idUser);
            ViewBag.denuncias = db.Denuncias.Where(d => d.idDenunciante == usuario.Id).ToList();
            return View();
        }

        public ActionResult Alumno()
        {
            return View();
        }

        public ActionResult Profesor()
        {
            return View();
        }

        public ActionResult Servicios()
        {
            return View();
        }

        [Authorize]
        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DE/ADES/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<hgroup>
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>
<div class="row-fluid">
    <div class="span12">
        <p>Use this area to provide additional information.</p>
    </div>
</div>

DE/ADES/Views/Home/AsignacionHoras.cshtml





<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Asignación de horas</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form id="form" action="#" class="wizard-big">
                        <div class="row">
                            <div class="col-lg-3">

                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Seleccionar periodo a trabajar</label>
                                    <input list="Civils" name="Civil" class="form-control col-lg-4">
                                    <datalist id="Civils">
                                        <option value="Soltero">
                                        <option value="Casado">
                                    </datalist>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Seleccionar periodo a trabajar</label>
                                    <input list="Civils" name="Civil" class="form-control col-lg-4">
                                    <datalist id="Civils">
                                        <option value="Soltero">
                                        <option value="Casado">
                                    </datalist>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Seleccionar carrera</label>
                                    <input list="Civils" name="Civil" class="form-control col-lg-4">
                                    <datalist id="Civils">
                                        <option value="Soltero">
                                        <option value="Casado">
                                    </datalist>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Seleccionar cuatrimestre</label>
                                    <input list="Civils" name="Civil" class="form-control col-lg-4">
                                    <datalist id="Civils">
                                        <option value="Soltero">
                                        <option value="Casado">
                                    </datalist>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Seleccionar grupo</label>
                                    <input list="Civils" name="Civil" class="form-control col-lg-4">
                                    <datalist id="Civils">
                                        <option value="Soltero">
                                        <option value="Casado">
                                    </datalist>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Seleccionar turno</label>
                                    <input list="Civils" name="Civil" class="form-control col-lg-4">
                                    <datalist id="Civils">
                                        <option value="Soltero">
                                        <option value="Casado">
                                    </datalist>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Seleccionar turno</label>
                                    <input list="Civils" name="Civil" class="form-control col-lg-4">
                                    <datalist id="Civils">
                                        <option value="Soltero">
                                        <option value="Casado">
                                    </datalist>
                                </div>
                            </div>
                        </div>
                        <label>Horarios</label>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <input id="domicilio" name="domicilio" type="text" class="form-control ">
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="form-group">
                                    <button type="button" id="crear" class="col-lg-1 btn btn-primary btn-circle" aria-hidden="true" data-toggle="modal" data-target="#create-modal">+</button>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom:15px;">
                            <div class="col-lg-12" style="border-bottom: 2px solid #ccc; padding-bottom:15px;">

                            </div>
                        </div>
                        <div class="row">
                            <table class="table table-striped table-bordered table-hover dataTables-example">
                                <thead>
                                    <tr>
                                    <tr>
                                        <th>
                                            Periodo
                                        </th>
                                        <th>
                                            Carrera
                                        </th>
                                        <th>
                                            Área
                                        </th>
                                        <th>
                                            Cuatrimestre
                                        </th>
                                        <th>
                                            Grupo
                                        </th>
                                        <th>
                                            Salón
                                        </th>
                                        <th>
                                            Acción
                                        </th>

                                    </tr>
                                </thead>
                                <tbody>

                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                            </table>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

DE/ADES/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<hgroup>
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>
<div>
    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <i class="icon-envelope"></i><strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <i class="icon-envelope"></i><strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</div>

DE/ADES/Views/Home/Dashboard.cshtml

@{
    ViewBag.Title = "Dashboard";
}

<div class="wrapper wrapper-content">
    <div class="row animated fadeInDown">
        <div class="col-lg-3">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Denuncias</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div id='external-events'>
                            @foreach (var item in ViewBag.denuncias)
                            {
                            <div class='external-event navy-bg'><a class="btn btn-link" href="@Url.Action("Pdf","Denuncias", new { id = item.id })"><i class="fa fa-file-pdf-o" aria-hidden="true"></i></a>@item.TipoDenuncia.nombre (@item.fecha.ToShortDateString())</div>
                            }
                        
                    </div>
                </div>
            </div>
            <!--<div class="ibox float-e-margins">
                <div class="ibox-content">
                    <h2>FullCalendar</h2> is a jQuery plugin that provides a full-sized, drag & drop calendar like the one below. It uses AJAX to fetch events on-the-fly for each month and is
                    easily configured to use your own feed format (an extension is provided for Google Calendar).
                    <p>
                        <a href="http://arshaw.com/fullcalendar/" target="_blank">FullCalendar documentation</a>
                    </p>
                </div>
            </div>-->
        </div>
        <div class="col-lg-9">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Calendario de ampliación de denuncias</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div id="calendar"></div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/plugins/fullCalendar")

<script>

    $(document).ready(function() {

            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green'
            });

        /* initialize the external events
         -----------------------------------------------------------------*/


        $('#external-events div.external-event').each(function() {

            // store data so the calendar knows to render an event upon drop
            $(this).data('event', {
                title: $.trim($(this).text()), // use the element's text as the event title
                stick: true // maintain when user navigates (see docs on the renderEvent method)
            });

            // make the event draggable using jQuery UI
            $(this).draggable({
                zIndex: 1111999,
                revert: true,      // will cause the event to go back to its
                revertDuration: 0  //  original position after the drag
            });

        });


        /* initialize the calendar
         -----------------------------------------------------------------*/
        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();

        $('#calendar').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            editable: true,
            droppable: true, // this allows things to be dropped onto the calendar
            drop: function() {
                // is the "remove after drop" checkbox checked?
               // if ($('#drop-remove').is(':checked')) {
                    // if so, remove the element from the "Draggable Events" list
                    $(this).remove();
                //}
            },
            events: [
                
            ]
        });


    });

</script>
}